### ISSUE TITLE
Google Search prompt should function instead of receiving "Internal Server Error"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#19]
Screenshot Example

![Google_Search_prompt_results_internal_server_error](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/a5fca38f-7bee-4985-ba08-9d3a8f63b555)

**Comment by b-solution** [comment]
@LAlexMHllc This one is working fine on my side, I've tested it several times.

**Comment by LAlexMHllc** [comment]
Closing, since the Internal Server Error does not display with Google Search Plugin Keys
