### ISSUE TITLE
Should include arrow up link with return to top function (like arrow down link with go to bottom function)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#20]
Screenshot Example

![should_include_arrowup_link_with_return_to_top_function](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/5bd5c8d7-7985-4e2d-82de-e5fee9f7c791)

**Comment by b-solution** [comment]
I was fixed that issue. Please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Closing, fixed
