### ISSUE TITLE
All Message Prompt container links should have tooltips and same style hover effect

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#21]
Screenshot Example

![message_prompt_selector_container_2](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/5a5c90ef-bf83-4b25-a626-e8a6cdd46a2b)

![message_prompt_selector_container](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/3de858a2-cd5b-4799-9a6d-112ab83d70ec)

**Comment by b-solution** [comment]
Can you please test it again.
