### ISSUE TITLE
Arrow Up and Arrow Down links should not display unless vertical scrollbar is displayed

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#24]
Screenshot Example

![arrow-up_and_arrow-down_links_should_not_display_unless_vertical_scrollbar_displays](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/8bdb532c-c195-409b-814e-1e7400e97f3d)

**Comment by LAlexMHllc** [comment]
See related Issue #20

**Comment by b-solution** [comment]
Can you please test it again. @LAlexMHllc

**Comment by LAlexMHllc** [comment]
Closing, fixed
