### ISSUE TITLE
Saved prompts should be retained until deleted

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#26]
Screenshot Example

![saved_prompts_should_remain_until_deleted](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/e43af6ad-0077-4326-8e3c-038cbef6f723)

**Comment by bluenevus** [comment]
Even worse, it seems that the prompts only save to a local computer vs the account.  That is it doesn't persist so when I go from computer to computer its still there

**Comment by LAlexMHllc** [comment]
Inconsistent behavior. Sometimes the prompts do not display on the sidebars after user logs back in to the same or different browser.
Yet, when the user inputs "/" into the message textbox, the saved prompts display as options.
Screenshot Example

![missing_saved_prompt_links_sidebar_yet_accessible_from_message_textbox](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/86435f19-27ad-4837-b3c4-7925b40b25d7)
