### ISSUE TITLE
Chat Search filter should function correctly

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#35]
Screenshot Example

![chat_Search_filter_should_function_correctly](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/4f68f1da-791a-46f3-81e5-ca476c4355c1)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by LAlexMHllc** [comment]
Search should also filter Chat Titles within folders. Search filter for Chat Titles outside of folders is inconsistent.
Screenshot Example

![Chat_Search_should_function](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/5a504fb7-db8a-4a9a-9949-260a261183c0)

**Comment by LAlexMHllc** [comment]
Search within Chat Folder still does not function.
Screenshot Example

![Chat_Search_should_function_2](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/e3160763-8067-407a-b1aa-45e4743b81b3)

**Comment by b-solution** [comment]
I'v fixed that issue please test it again and let me know if not working good.
