### ISSUE TITLE
As a user I would like to be able to upload pdf, word and excel documents for analysis 

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/chatbot-ui#4]
As a user I would like to be able to upload pdf, word and excel documents for analysis like so though I’m don’t want an extension but these functions[ [https://chrome.google.com/webstore/detail/chatgpt-file-uploader-ext/becfinhbfclcgokjlobojlnldbfillpf/]]

**Comment by LAlexMHllc** [comment]
Uploaded small XLXS doc, received token error message.
Screenshot Example

![upload_XLSCdoc_error](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/ab3b201a-8298-4827-90d0-fda6900658a5)

**Comment by LAlexMHllc** [comment]
Uploaded small PDF doc, received token error message.
Screenshot Example

![upload_PDFdoc_error](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/a1046aa7-3432-41d3-9b7c-56524c8f919e)

**Comment by LAlexMHllc** [comment]
Was expecting legible text

**Comment by bluenevus** [comment]
it completely didn't work at all for me either...nothing but jibberish.  Din't even work when uploading a text file...jibberish and definitely not a pdf

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Closing, since was able to upload files in formats Excel, PDF, and Word, and received a response for all.

**Comment by LAlexMHllc** [comment]
Does not function correctly with really large files.
