### ISSUE TITLE
we are 43 commits behind. 

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/chatbot-ui#40]
we are 43 commits behind.  can we evaluate those commits determine the value, merge the commits we need but not break the features we added?

This branch is out-of-date
Update branch to merge the latest changes from the upstream repository into this branch.

Discard 43 commits to make this branch match the upstream repository. 43 commits will be removed from this branch.

**Comment by jldroid19** [comment]
@bluenevus the repo this app originated from has been abandoned. I think from this point on we should only welcome changes from like repos.

**Comment by jldroid19** [comment]
The repo this application was originally forked from appears to be abandoned. Closing this request now!
