### ISSUE TITLE
xlsx package is considered high risk and there is no fix available

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/chatbot-ui#42]
we will need to use a different package dependency as the severity on this module is high

**Comment by jldroid19** [comment]
@bluenevus I am seeing the same results. Also, when runnign the build it is very inconsistent. 
npm install
npm run dev

I get a Module not found: Can't resolve 'XLSX'

npm list > result: └── xlsx@0.18.5

The module is indeed there on my system.

This build is too unstable to deploy.

**Comment by jldroid19** [comment]
@b-solution I sent you an email regarding the xlsx package breaking the main branch. Please create a new branch strip out any xlsx dependencies you've applied and push the new branch up without the xlsx dependency. This way we can baseline the app and work the xlsx on a different branch.

**Comment by jldroid19** [comment]
@b-solution Thanks for fixing the build errors.
