### ISSUE TITLE
As a user I would like to be able to export the data into word or excel documents

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/chatbot-ui#5]
As a user I would like to be able to export the data into word or excel documents kind of like so but without a chrome plugin and for word and excel [https://chrome.google.com/webstore/detail/chatgpt-file-uploader-ext/becfinhbfclcgokjlobojlnldbfillpf/]

**Comment by LAlexMHllc** [comment]
Clicked both Export data links, and no file downloaded.
Screenshot Example

![export_data_function_not_working](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/8f451207-42c7-4edf-b186-625da16dc046)

**Comment by b-solution** [comment]
Can you please test it again. I was fixed that issue.

**Comment by LAlexMHllc** [comment]
Closing, since files downloaded in both formats
